on:
  release:
    types: [created, edited]

jobs:
  release_html5:
    runs-on: ubuntu-latest
    steps:
      - name: download html5
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: SpritelessJerks_HTML5.zip
        env:
          GITHUB_TOKEN: "${{ secrets.EXPORT_GITHUB_TOKEN }}"
      - name: release html5
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: spriteless-jerks
          ITCH_USER: GrandInquisitor
          PACKAGE: SpritelessJerks_HTML5.zip